### ISSUE TITLE
Support inexact tarball name specification for loading

### ISSUE THREAD

**Issue by rjschwei** [OSInside/flake-pilot#49]
When loading a container one should be able to specify a partial name for the tarball. For example let's assume `/usr/share/suse-docker-images/native/aws-cli.x86_64-0.1.1-Build1.1.docker.tar` exists but the file is to be loaded through a %post action in an RPM package where we cannot determine the version string. As such being able to specify

`flake-ctl podman load --oci /usr/share/suse-docker-images/native/aws-cli`

would be very convenient and `flake-ctl` can sort out the container to load. If multiple tarballs that match the glob exist the latest version should be loaded to match the default behavior of container runtimes which also always use what is tagged as latest.

**Comment by schaefi** [comment]
Fixed with d89451c6fb3a16b761bb104c3cddeb691fbb3690
